// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbr14QajgZ-FKsPQPydWRwcRXEKmztjDA',
    appId: '1:539396715832:web:9698e219796e10e951fdcd',
    messagingSenderId: '539396715832',
    projectId: 'flutter--analytics-fe070',
    authDomain: 'flutter--analytics-fe070.firebaseapp.com',
    storageBucket: 'flutter--analytics-fe070.appspot.com',
    measurementId: 'G-1C13E3JYRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFyOhCgqSWMZpd6Ay7jag1MGD8CbigyfM',
    appId: '1:539396715832:android:38723c5793adb9d651fdcd',
    messagingSenderId: '539396715832',
    projectId: 'flutter--analytics-fe070',
    storageBucket: 'flutter--analytics-fe070.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo-Ij3EzhzOzqnH-YRvQe-XO9LOG1b4xU',
    appId: '1:539396715832:ios:61a50f0d4d4ef0dc51fdcd',
    messagingSenderId: '539396715832',
    projectId: 'flutter--analytics-fe070',
    storageBucket: 'flutter--analytics-fe070.appspot.com',
    iosClientId: '539396715832-garodkmtgmj9e0atjq1l62bd6v5b9p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAnalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo-Ij3EzhzOzqnH-YRvQe-XO9LOG1b4xU',
    appId: '1:539396715832:ios:61a50f0d4d4ef0dc51fdcd',
    messagingSenderId: '539396715832',
    projectId: 'flutter--analytics-fe070',
    storageBucket: 'flutter--analytics-fe070.appspot.com',
    iosClientId: '539396715832-garodkmtgmj9e0atjq1l62bd6v5b9p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGoogleAnalytics',
  );
}
